[project]
name = "match_to_proposal"
version = "0.1.0"
description = "match_to_proposal using crewAI"
authors = [{name = "Your Name", email = "you@example.com"}]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "crewai[tools]>=0.152.0",
    "crewai-tools>=0.58.0",
    "jinja2 (>=3.1.6,<4.0.0)",
]

[project.scripts]
match_to_proposal = "match_to_proposal.main:run"
train = "match_to_proposal.main:train"
