[tool.poetry]
name = "trip-planner-crew"
version = "0.1.0"
description = ""
authors = ["Sergei Ovsiannikov <you@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10.0,<3.12"
crewai = ">=0.152.0"
unstructured = "0.10.25"
pyowm = "3.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
